export type StateCode = keyof typeof stateTaxRates;

/** Top marginal state income tax rates (approximate, 2024/25). */
export const stateTaxRates = {
  AL: 5.0,
  AK: 0,
  AZ: 2.5,
  AR: 4.4,
  CA: 9.3,
  CO: 4.4,
  CT: 6.99,
  DE: 6.6,
  FL: 0,
  GA: 5.49,
  HI: 11.0,
  ID: 5.8,
  IL: 4.95,
  IN: 3.05,
  IA: 5.7,
  KS: 5.7,
  KY: 4.0,
  LA: 4.25,
  ME: 7.15,
  MD: 5.75,
  MA: 5.0,
  MI: 4.25,
  MN: 9.85,
  MS: 4.7,
  MO: 4.8,
  MT: 5.9,
  NE: 5.84,
  NV: 0,
  NH: 0,
  NJ: 10.75,
  NM: 5.9,
  NY: 10.9,
  NC: 4.5,
  ND: 2.5,
  OH: 3.5,
  OK: 4.75,
  OR: 9.9,
  PA: 3.07,
  RI: 5.99,
  SC: 6.4,
  SD: 0,
  TN: 0,
  TX: 0,
  UT: 4.65,
  VT: 8.75,
  VA: 5.75,
  WA: 0,
  WV: 5.12,
  WI: 7.65,
  WY: 0,
  DC: 10.75,
} as const;

export const stateNames: Record<StateCode, string> = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
  DC: "Washington D.C.",
};
